server:
    port: 8081


spring:
  datasource:
      driver-class-name: org.postgresql.Driver 
      url: jdbc:postgresql://127.0.0.1:5433/proyecto
      username: postgres
      password: viniciocc16
jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
